# import baseImage
FROM alpine:latest

#membuat direktori
RUN mkdir latihan
# Menulis move some data into a file
RUN echo "This is Sugeng Wahyudi Image" > "latihan/latihan.txt" && echo "Belajar Docker"> "latihan/latihan1.txt"
#menampilkan isi, ist the contents of a file on the standard output
CMD cat "latihan/latihan.txt" "latihan/latihan1.txt"