FROM alpine:latest
#FROM python:3.7-alpine

#membuar folder
RUN mkdir text
#menambahkan python script ke folder pyscript
COPY script/*.txt text


#jalankan saat dibuat container
CMD cat  "text/text2.txt" "text/text1.txt"